services:
  ui:
    build: .
    expose:
      - 7001
    volumes:
      - ./src/:/app/src/
      - /app/.venv
    command: streamlit run src/options/app.py
    environment:
      - VIRTUAL_HOST=choptions.charlieavery.site
    networks:
      - web

networks:
  web:
    external: true