services:
  ui:
    build: .
    expose:
      - 8501
    volumes:
      - ./src/:/app/src/
      - /app/.venv
    command: streamlit run src/options/app.py
    networks:
      - web

  nginx:
    build: ./nginx
    expose:
      - 80
    depends_on:
      - ui
    environment:
      - VIRTUAL_HOST=choptions.charlieavery.site
      - LETSENCRYPT_HOST=choptions.charlieavery.site
    networks:
      - web

networks:
  web:
    external: true